// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _worker_create_COO_HH_
#define _worker_create_COO_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "worker_fcmp_32ns_32ns_1_1.h"
#include "worker_urem_7ns_6ns_7_11_seq.h"
#include "worker_mux_16to1_sel5_32_1.h"
#include "worker_create_COO_matrix_1_0_0.h"
#include "worker_create_COO_matrix_1_0_1.h"
#include "worker_create_COO_matrix_1_0_2.h"
#include "worker_create_COO_matrix_1_0_3.h"
#include "worker_create_COO_matrix_1_1_0.h"
#include "worker_create_COO_matrix_1_1_1.h"
#include "worker_create_COO_matrix_1_1_2.h"
#include "worker_create_COO_matrix_1_1_3.h"
#include "worker_create_COO_matrix_1_2_0.h"
#include "worker_create_COO_matrix_1_2_1.h"
#include "worker_create_COO_matrix_1_2_2.h"
#include "worker_create_COO_matrix_1_2_3.h"
#include "worker_create_COO_matrix_1_3_0.h"
#include "worker_create_COO_matrix_1_3_1.h"
#include "worker_create_COO_matrix_1_3_2.h"
#include "worker_create_COO_matrix_1_3_3.h"
#include "worker_create_COO_temp_row.h"
#include "worker_create_COO_temp_val.h"

namespace ap_rtl {

struct worker_create_COO : public sc_module {
    // Port declarations 20
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<12> > row_address0;
    sc_out< sc_logic > row_ce0;
    sc_out< sc_logic > row_we0;
    sc_out< sc_lv<7> > row_d0;
    sc_out< sc_lv<12> > col_address0;
    sc_out< sc_logic > col_ce0;
    sc_out< sc_logic > col_we0;
    sc_out< sc_lv<7> > col_d0;
    sc_out< sc_lv<12> > val_r_address0;
    sc_out< sc_logic > val_r_ce0;
    sc_out< sc_logic > val_r_we0;
    sc_out< sc_lv<32> > val_r_d0;
    sc_in< sc_lv<8> > block_r;
    sc_out< sc_lv<32> > ap_return;
    sc_signal< sc_logic > ap_var_for_const2;
    sc_signal< sc_lv<32> > ap_var_for_const0;
    sc_signal< sc_lv<5> > ap_var_for_const1;


    // Module declarations
    worker_create_COO(sc_module_name name);
    SC_HAS_PROCESS(worker_create_COO);

    ~worker_create_COO();

    sc_trace_file* mVcdFile;

    worker_create_COO_matrix_1_0_0* matrix_1_0_0_U;
    worker_create_COO_matrix_1_0_1* matrix_1_0_1_U;
    worker_create_COO_matrix_1_0_2* matrix_1_0_2_U;
    worker_create_COO_matrix_1_0_3* matrix_1_0_3_U;
    worker_create_COO_matrix_1_1_0* matrix_1_1_0_U;
    worker_create_COO_matrix_1_1_1* matrix_1_1_1_U;
    worker_create_COO_matrix_1_1_2* matrix_1_1_2_U;
    worker_create_COO_matrix_1_1_3* matrix_1_1_3_U;
    worker_create_COO_matrix_1_2_0* matrix_1_2_0_U;
    worker_create_COO_matrix_1_2_1* matrix_1_2_1_U;
    worker_create_COO_matrix_1_2_2* matrix_1_2_2_U;
    worker_create_COO_matrix_1_2_3* matrix_1_2_3_U;
    worker_create_COO_matrix_1_3_0* matrix_1_3_0_U;
    worker_create_COO_matrix_1_3_1* matrix_1_3_1_U;
    worker_create_COO_matrix_1_3_2* matrix_1_3_2_U;
    worker_create_COO_matrix_1_3_3* matrix_1_3_3_U;
    worker_create_COO_temp_row* temp_row_U;
    worker_create_COO_temp_row* temp_col_U;
    worker_create_COO_temp_val* temp_val_U;
    worker_fcmp_32ns_32ns_1_1<1,1,32,32,1>* worker_fcmp_32ns_32ns_1_1_U1;
    worker_urem_7ns_6ns_7_11_seq<1,11,7,6,7>* worker_urem_7ns_6ns_7_11_seq_U2;
    worker_mux_16to1_sel5_32_1<1,1,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,5,32>* worker_mux_16to1_sel5_32_1_U3;
    sc_signal< sc_lv<18> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_35;
    sc_signal< sc_lv<10> > matrix_1_0_0_address0;
    sc_signal< sc_logic > matrix_1_0_0_ce0;
    sc_signal< sc_lv<32> > matrix_1_0_0_q0;
    sc_signal< sc_lv<10> > matrix_1_0_1_address0;
    sc_signal< sc_logic > matrix_1_0_1_ce0;
    sc_signal< sc_lv<32> > matrix_1_0_1_q0;
    sc_signal< sc_lv<10> > matrix_1_0_2_address0;
    sc_signal< sc_logic > matrix_1_0_2_ce0;
    sc_signal< sc_lv<32> > matrix_1_0_2_q0;
    sc_signal< sc_lv<10> > matrix_1_0_3_address0;
    sc_signal< sc_logic > matrix_1_0_3_ce0;
    sc_signal< sc_lv<32> > matrix_1_0_3_q0;
    sc_signal< sc_lv<10> > matrix_1_1_0_address0;
    sc_signal< sc_logic > matrix_1_1_0_ce0;
    sc_signal< sc_lv<32> > matrix_1_1_0_q0;
    sc_signal< sc_lv<10> > matrix_1_1_1_address0;
    sc_signal< sc_logic > matrix_1_1_1_ce0;
    sc_signal< sc_lv<32> > matrix_1_1_1_q0;
    sc_signal< sc_lv<10> > matrix_1_1_2_address0;
    sc_signal< sc_logic > matrix_1_1_2_ce0;
    sc_signal< sc_lv<32> > matrix_1_1_2_q0;
    sc_signal< sc_lv<10> > matrix_1_1_3_address0;
    sc_signal< sc_logic > matrix_1_1_3_ce0;
    sc_signal< sc_lv<32> > matrix_1_1_3_q0;
    sc_signal< sc_lv<10> > matrix_1_2_0_address0;
    sc_signal< sc_logic > matrix_1_2_0_ce0;
    sc_signal< sc_lv<32> > matrix_1_2_0_q0;
    sc_signal< sc_lv<10> > matrix_1_2_1_address0;
    sc_signal< sc_logic > matrix_1_2_1_ce0;
    sc_signal< sc_lv<32> > matrix_1_2_1_q0;
    sc_signal< sc_lv<10> > matrix_1_2_2_address0;
    sc_signal< sc_logic > matrix_1_2_2_ce0;
    sc_signal< sc_lv<32> > matrix_1_2_2_q0;
    sc_signal< sc_lv<10> > matrix_1_2_3_address0;
    sc_signal< sc_logic > matrix_1_2_3_ce0;
    sc_signal< sc_lv<32> > matrix_1_2_3_q0;
    sc_signal< sc_lv<10> > matrix_1_3_0_address0;
    sc_signal< sc_logic > matrix_1_3_0_ce0;
    sc_signal< sc_lv<32> > matrix_1_3_0_q0;
    sc_signal< sc_lv<10> > matrix_1_3_1_address0;
    sc_signal< sc_logic > matrix_1_3_1_ce0;
    sc_signal< sc_lv<32> > matrix_1_3_1_q0;
    sc_signal< sc_lv<10> > matrix_1_3_2_address0;
    sc_signal< sc_logic > matrix_1_3_2_ce0;
    sc_signal< sc_lv<32> > matrix_1_3_2_q0;
    sc_signal< sc_lv<10> > matrix_1_3_3_address0;
    sc_signal< sc_logic > matrix_1_3_3_ce0;
    sc_signal< sc_lv<32> > matrix_1_3_3_q0;
    sc_signal< sc_lv<7> > tmp_8_fu_497_p1;
    sc_signal< sc_lv<7> > tmp_8_reg_857;
    sc_signal< sc_lv<5> > i_3_fu_516_p2;
    sc_signal< sc_lv<5> > i_3_reg_865;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_187;
    sc_signal< sc_lv<7> > tmp_fu_522_p2;
    sc_signal< sc_lv<7> > tmp_reg_870;
    sc_signal< sc_lv<1> > exitcond2_fu_510_p2;
    sc_signal< sc_lv<7> > grp_fu_527_p2;
    sc_signal< sc_lv<7> > newIndex_reg_891;
    sc_signal< sc_logic > ap_sig_cseq_ST_st12_fsm_11;
    sc_signal< bool > ap_sig_202;
    sc_signal< sc_lv<10> > tmp_13_fu_555_p2;
    sc_signal< sc_lv<10> > tmp_13_reg_896;
    sc_signal< sc_logic > ap_sig_cseq_ST_st13_fsm_12;
    sc_signal< bool > ap_sig_211;
    sc_signal< sc_lv<4> > tmp_4_fu_571_p3;
    sc_signal< sc_lv<4> > tmp_4_reg_901;
    sc_signal< sc_lv<7> > j_1_fu_585_p2;
    sc_signal< sc_lv<7> > j_1_reg_909;
    sc_signal< sc_logic > ap_sig_cseq_ST_st14_fsm_13;
    sc_signal< bool > ap_sig_222;
    sc_signal< sc_lv<15> > next_mul_fu_591_p2;
    sc_signal< sc_lv<15> > next_mul_reg_914;
    sc_signal< sc_lv<1> > exitcond1_fu_579_p2;
    sc_signal< sc_lv<4> > tmp_7_fu_640_p2;
    sc_signal< sc_lv<4> > tmp_7_reg_999;
    sc_signal< sc_lv<32> > tmp_3_fu_648_p18;
    sc_signal< sc_lv<32> > tmp_3_reg_1004;
    sc_signal< sc_logic > ap_sig_cseq_ST_st15_fsm_14;
    sc_signal< bool > ap_sig_270;
    sc_signal< sc_lv<7> > idx_urem_fu_757_p3;
    sc_signal< sc_logic > ap_sig_cseq_ST_st16_fsm_15;
    sc_signal< bool > ap_sig_279;
    sc_signal< sc_lv<12> > i_2_fu_775_p2;
    sc_signal< sc_lv<12> > i_2_reg_1022;
    sc_signal< sc_logic > ap_sig_cseq_ST_st17_fsm_16;
    sc_signal< bool > ap_sig_288;
    sc_signal< sc_lv<32> > counter_load_1_reg_1027;
    sc_signal< sc_lv<1> > exitcond_fu_769_p2;
    sc_signal< sc_lv<1> > tmp_5_fu_781_p2;
    sc_signal< sc_lv<1> > tmp_5_reg_1032;
    sc_signal< sc_lv<14> > temp_row_address0;
    sc_signal< sc_logic > temp_row_ce0;
    sc_signal< sc_logic > temp_row_we0;
    sc_signal< sc_lv<7> > temp_row_q0;
    sc_signal< sc_lv<14> > temp_col_address0;
    sc_signal< sc_logic > temp_col_ce0;
    sc_signal< sc_logic > temp_col_we0;
    sc_signal< sc_lv<7> > temp_col_q0;
    sc_signal< sc_lv<14> > temp_val_address0;
    sc_signal< sc_logic > temp_val_ce0;
    sc_signal< sc_logic > temp_val_we0;
    sc_signal< sc_lv<32> > temp_val_q0;
    sc_signal< sc_lv<5> > i_reg_431;
    sc_signal< sc_lv<7> > j_reg_442;
    sc_signal< sc_lv<15> > phi_mul_reg_455;
    sc_signal< sc_lv<7> > phi_urem_reg_466;
    sc_signal< sc_lv<12> > i1_reg_478;
    sc_signal< sc_logic > ap_sig_cseq_ST_st18_fsm_17;
    sc_signal< bool > ap_sig_359;
    sc_signal< sc_lv<64> > tmp_15_cast_fu_606_p1;
    sc_signal< sc_lv<64> > tmp_2_fu_727_p1;
    sc_signal< sc_lv<1> > tmp_12_fu_721_p2;
    sc_signal< sc_lv<64> > tmp_9_fu_787_p1;
    sc_signal< sc_lv<64> > tmp_s_fu_800_p1;
    sc_signal< sc_lv<32> > counter_fu_116;
    sc_signal< sc_lv<32> > counter_1_fu_734_p2;
    sc_signal< sc_lv<32> > cur_ind_1_fu_132;
    sc_signal< sc_lv<32> > start_0_s_fu_832_p3;
    sc_signal< sc_lv<32> > cur_ind_fu_136;
    sc_signal< sc_lv<32> > p_start_fu_824_p3;
    sc_signal< sc_lv<7> > i_cast3_fu_506_p1;
    sc_signal< sc_lv<7> > grp_fu_527_p0;
    sc_signal< sc_lv<6> > grp_fu_527_p1;
    sc_signal< sc_lv<7> > mul_fu_546_p0;
    sc_signal< sc_lv<6> > tmp_13_fu_555_p0;
    sc_signal< sc_lv<16> > mul_fu_546_p2;
    sc_signal< sc_lv<2> > tmp_14_fu_561_p4;
    sc_signal< sc_lv<10> > newIndex2_cast_fu_597_p1;
    sc_signal< sc_lv<10> > tmp_15_fu_601_p2;
    sc_signal< sc_lv<3> > tmp_16_fu_626_p4;
    sc_signal< sc_lv<4> > tmp_6_cast_fu_636_p1;
    sc_signal< sc_lv<5> > tmp_3_fu_648_p17;
    sc_signal< sc_lv<32> > p_to_int_fu_686_p1;
    sc_signal< sc_lv<8> > tmp_6_fu_689_p4;
    sc_signal< sc_lv<23> > tmp_17_fu_699_p1;
    sc_signal< sc_lv<1> > notrhs_fu_709_p2;
    sc_signal< sc_lv<1> > notlhs_fu_703_p2;
    sc_signal< sc_lv<1> > tmp_10_fu_715_p2;
    sc_signal< sc_lv<1> > tmp_11_fu_489_p2;
    sc_signal< sc_lv<7> > next_urem_fu_745_p2;
    sc_signal< sc_lv<1> > tmp_18_fu_751_p2;
    sc_signal< sc_lv<32> > i1_cast1_fu_765_p1;
    sc_signal< sc_lv<32> > cur_ind_2_fu_807_p2;
    sc_signal< sc_lv<1> > tmp_1_fu_813_p2;
    sc_signal< sc_lv<32> > start_fu_818_p2;
    sc_signal< sc_logic > grp_fu_527_ap_start;
    sc_signal< sc_logic > grp_fu_527_ap_done;
    sc_signal< sc_lv<18> > ap_NS_fsm;
    sc_signal< sc_lv<16> > mul_fu_546_p00;
    sc_signal< sc_lv<10> > tmp_13_fu_555_p00;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<18> ap_ST_st1_fsm_0;
    static const sc_lv<18> ap_ST_st2_fsm_1;
    static const sc_lv<18> ap_ST_st3_fsm_2;
    static const sc_lv<18> ap_ST_st4_fsm_3;
    static const sc_lv<18> ap_ST_st5_fsm_4;
    static const sc_lv<18> ap_ST_st6_fsm_5;
    static const sc_lv<18> ap_ST_st7_fsm_6;
    static const sc_lv<18> ap_ST_st8_fsm_7;
    static const sc_lv<18> ap_ST_st9_fsm_8;
    static const sc_lv<18> ap_ST_st10_fsm_9;
    static const sc_lv<18> ap_ST_st11_fsm_10;
    static const sc_lv<18> ap_ST_st12_fsm_11;
    static const sc_lv<18> ap_ST_st13_fsm_12;
    static const sc_lv<18> ap_ST_st14_fsm_13;
    static const sc_lv<18> ap_ST_st15_fsm_14;
    static const sc_lv<18> ap_ST_st16_fsm_15;
    static const sc_lv<18> ap_ST_st17_fsm_16;
    static const sc_lv<18> ap_ST_st18_fsm_17;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<15> ap_const_lv15_0;
    static const sc_lv<12> ap_const_lv12_0;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<5> ap_const_lv5_19;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<7> ap_const_lv7_19;
    static const sc_lv<16> ap_const_lv16_A4;
    static const sc_lv<10> ap_const_lv10_19;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<7> ap_const_lv7_64;
    static const sc_lv<7> ap_const_lv7_1;
    static const sc_lv<15> ap_const_lv15_A4;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<23> ap_const_lv23_0;
    static const sc_lv<12> ap_const_lv12_9C4;
    static const sc_lv<12> ap_const_lv12_1;
    static const sc_lv<32> ap_const_lv32_8;
    // Thread declarations
    void thread_ap_var_for_const2();
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_ap_sig_187();
    void thread_ap_sig_202();
    void thread_ap_sig_211();
    void thread_ap_sig_222();
    void thread_ap_sig_270();
    void thread_ap_sig_279();
    void thread_ap_sig_288();
    void thread_ap_sig_35();
    void thread_ap_sig_359();
    void thread_ap_sig_cseq_ST_st12_fsm_11();
    void thread_ap_sig_cseq_ST_st13_fsm_12();
    void thread_ap_sig_cseq_ST_st14_fsm_13();
    void thread_ap_sig_cseq_ST_st15_fsm_14();
    void thread_ap_sig_cseq_ST_st16_fsm_15();
    void thread_ap_sig_cseq_ST_st17_fsm_16();
    void thread_ap_sig_cseq_ST_st18_fsm_17();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_col_address0();
    void thread_col_ce0();
    void thread_col_d0();
    void thread_col_we0();
    void thread_counter_1_fu_734_p2();
    void thread_cur_ind_2_fu_807_p2();
    void thread_exitcond1_fu_579_p2();
    void thread_exitcond2_fu_510_p2();
    void thread_exitcond_fu_769_p2();
    void thread_grp_fu_527_ap_start();
    void thread_grp_fu_527_p0();
    void thread_grp_fu_527_p1();
    void thread_i1_cast1_fu_765_p1();
    void thread_i_2_fu_775_p2();
    void thread_i_3_fu_516_p2();
    void thread_i_cast3_fu_506_p1();
    void thread_idx_urem_fu_757_p3();
    void thread_j_1_fu_585_p2();
    void thread_matrix_1_0_0_address0();
    void thread_matrix_1_0_0_ce0();
    void thread_matrix_1_0_1_address0();
    void thread_matrix_1_0_1_ce0();
    void thread_matrix_1_0_2_address0();
    void thread_matrix_1_0_2_ce0();
    void thread_matrix_1_0_3_address0();
    void thread_matrix_1_0_3_ce0();
    void thread_matrix_1_1_0_address0();
    void thread_matrix_1_1_0_ce0();
    void thread_matrix_1_1_1_address0();
    void thread_matrix_1_1_1_ce0();
    void thread_matrix_1_1_2_address0();
    void thread_matrix_1_1_2_ce0();
    void thread_matrix_1_1_3_address0();
    void thread_matrix_1_1_3_ce0();
    void thread_matrix_1_2_0_address0();
    void thread_matrix_1_2_0_ce0();
    void thread_matrix_1_2_1_address0();
    void thread_matrix_1_2_1_ce0();
    void thread_matrix_1_2_2_address0();
    void thread_matrix_1_2_2_ce0();
    void thread_matrix_1_2_3_address0();
    void thread_matrix_1_2_3_ce0();
    void thread_matrix_1_3_0_address0();
    void thread_matrix_1_3_0_ce0();
    void thread_matrix_1_3_1_address0();
    void thread_matrix_1_3_1_ce0();
    void thread_matrix_1_3_2_address0();
    void thread_matrix_1_3_2_ce0();
    void thread_matrix_1_3_3_address0();
    void thread_matrix_1_3_3_ce0();
    void thread_mul_fu_546_p0();
    void thread_mul_fu_546_p00();
    void thread_mul_fu_546_p2();
    void thread_newIndex2_cast_fu_597_p1();
    void thread_next_mul_fu_591_p2();
    void thread_next_urem_fu_745_p2();
    void thread_notlhs_fu_703_p2();
    void thread_notrhs_fu_709_p2();
    void thread_p_start_fu_824_p3();
    void thread_p_to_int_fu_686_p1();
    void thread_row_address0();
    void thread_row_ce0();
    void thread_row_d0();
    void thread_row_we0();
    void thread_start_0_s_fu_832_p3();
    void thread_start_fu_818_p2();
    void thread_temp_col_address0();
    void thread_temp_col_ce0();
    void thread_temp_col_we0();
    void thread_temp_row_address0();
    void thread_temp_row_ce0();
    void thread_temp_row_we0();
    void thread_temp_val_address0();
    void thread_temp_val_ce0();
    void thread_temp_val_we0();
    void thread_tmp_10_fu_715_p2();
    void thread_tmp_12_fu_721_p2();
    void thread_tmp_13_fu_555_p0();
    void thread_tmp_13_fu_555_p00();
    void thread_tmp_13_fu_555_p2();
    void thread_tmp_14_fu_561_p4();
    void thread_tmp_15_cast_fu_606_p1();
    void thread_tmp_15_fu_601_p2();
    void thread_tmp_16_fu_626_p4();
    void thread_tmp_17_fu_699_p1();
    void thread_tmp_18_fu_751_p2();
    void thread_tmp_1_fu_813_p2();
    void thread_tmp_2_fu_727_p1();
    void thread_tmp_3_fu_648_p17();
    void thread_tmp_4_fu_571_p3();
    void thread_tmp_5_fu_781_p2();
    void thread_tmp_6_cast_fu_636_p1();
    void thread_tmp_6_fu_689_p4();
    void thread_tmp_7_fu_640_p2();
    void thread_tmp_8_fu_497_p1();
    void thread_tmp_9_fu_787_p1();
    void thread_tmp_fu_522_p2();
    void thread_tmp_s_fu_800_p1();
    void thread_val_r_address0();
    void thread_val_r_ce0();
    void thread_val_r_d0();
    void thread_val_r_we0();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
