// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __worker_create_COO_matrix_1_3_3_H__
#define __worker_create_COO_matrix_1_3_3_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct worker_create_COO_matrix_1_3_3_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 625;
  static const unsigned AddressWidth = 10;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(worker_create_COO_matrix_1_3_3_ram) {
        for (unsigned i = 0; i < 34 ; i = i + 1) {
            ram[i] = "0b00000000000000000000000000000000";
        }
        ram[34] = "0b11000000010110101011100010010110";
        for (unsigned i = 35; i < 134 ; i = i + 1) {
            ram[i] = "0b00000000000000000000000000000000";
        }
        ram[134] = "0b10111111010000110111100100011000";
        for (unsigned i = 135; i < 147 ; i = i + 1) {
            ram[i] = "0b00000000000000000000000000000000";
        }
        ram[147] = "0b01000000110110110010101111101000";
        for (unsigned i = 148; i < 227 ; i = i + 1) {
            ram[i] = "0b00000000000000000000000000000000";
        }
        ram[227] = "0b11000000111011101111001001011001";
        for (unsigned i = 228; i < 347 ; i = i + 1) {
            ram[i] = "0b00000000000000000000000000000000";
        }
        ram[347] = "0b01000000101100001110010111010110";
        for (unsigned i = 348; i < 625 ; i = i + 1) {
            ram[i] = "0b00000000000000000000000000000000";
        }


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(worker_create_COO_matrix_1_3_3) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 625;
static const unsigned AddressWidth = 10;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


worker_create_COO_matrix_1_3_3_ram* meminst;


SC_CTOR(worker_create_COO_matrix_1_3_3) {
meminst = new worker_create_COO_matrix_1_3_3_ram("worker_create_COO_matrix_1_3_3_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~worker_create_COO_matrix_1_3_3() {
    delete meminst;
}


};//endmodule
#endif
