// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __worker_create_COO_matrix_1_0_0_H__
#define __worker_create_COO_matrix_1_0_0_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct worker_create_COO_matrix_1_0_0_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 625;
  static const unsigned AddressWidth = 10;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(worker_create_COO_matrix_1_0_0_ram) {
        for (unsigned i = 0; i < 27 ; i = i + 1) {
            ram[i] = "0b00000000000000000000000000000000";
        }
        ram[27] = "0b01000000101100011111100101110110";
        for (unsigned i = 28; i < 443 ; i = i + 1) {
            ram[i] = "0b00000000000000000000000000000000";
        }
        ram[443] = "0b11000001000011011111000000011100";
        for (unsigned i = 444; i < 539 ; i = i + 1) {
            ram[i] = "0b00000000000000000000000000000000";
        }
        ram[539] = "0b01000000110000010010010011000101";
        for (unsigned i = 540; i < 607 ; i = i + 1) {
            ram[i] = "0b00000000000000000000000000000000";
        }
        ram[607] = "0b11000001000100100000101000111101";
        for (unsigned i = 608; i < 617 ; i = i + 1) {
            ram[i] = "0b00000000000000000000000000000000";
        }
        ram[617] = "0b11000000111010001101000110100001";
        for (unsigned i = 618; i < 625 ; i = i + 1) {
            ram[i] = "0b00000000000000000000000000000000";
        }


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(worker_create_COO_matrix_1_0_0) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 625;
static const unsigned AddressWidth = 10;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


worker_create_COO_matrix_1_0_0_ram* meminst;


SC_CTOR(worker_create_COO_matrix_1_0_0) {
meminst = new worker_create_COO_matrix_1_0_0_ram("worker_create_COO_matrix_1_0_0_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~worker_create_COO_matrix_1_0_0() {
    delete meminst;
}


};//endmodule
#endif
