#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("dest_0_address0", 5, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("dest_0_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("dest_0_we0", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("dest_0_d0", 32, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("dest_0_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("dest_0_address1", 5, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("dest_0_ce1", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("dest_0_we1", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("dest_0_d1", 32, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("dest_1_address0", 5, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("dest_1_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("dest_1_we0", 1, hls_out, 1, "ap_memory", "mem_we", 1),
	Port_Property("dest_1_d0", 32, hls_out, 1, "ap_memory", "mem_din", 1),
	Port_Property("dest_1_q0", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("dest_1_address1", 5, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("dest_1_ce1", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("dest_1_we1", 1, hls_out, 1, "ap_memory", "mem_we", 1),
	Port_Property("dest_1_d1", 32, hls_out, 1, "ap_memory", "mem_din", 1),
	Port_Property("dest_2_address0", 5, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("dest_2_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("dest_2_we0", 1, hls_out, 2, "ap_memory", "mem_we", 1),
	Port_Property("dest_2_d0", 32, hls_out, 2, "ap_memory", "mem_din", 1),
	Port_Property("dest_2_q0", 32, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("dest_2_address1", 5, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("dest_2_ce1", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("dest_2_we1", 1, hls_out, 2, "ap_memory", "mem_we", 1),
	Port_Property("dest_2_d1", 32, hls_out, 2, "ap_memory", "mem_din", 1),
	Port_Property("dest_3_address0", 5, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("dest_3_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("dest_3_we0", 1, hls_out, 3, "ap_memory", "mem_we", 1),
	Port_Property("dest_3_d0", 32, hls_out, 3, "ap_memory", "mem_din", 1),
	Port_Property("dest_3_q0", 32, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("dest_3_address1", 5, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("dest_3_ce1", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("dest_3_we1", 1, hls_out, 3, "ap_memory", "mem_we", 1),
	Port_Property("dest_3_d1", 32, hls_out, 3, "ap_memory", "mem_din", 1),
};
const char* HLS_Design_Meta::dut_name = "worker";
