-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.2
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity worker_create_COO_matrix_1_1_1_rom is 
    generic(
             dwidth     : integer := 32; 
             awidth     : integer := 10; 
             mem_size    : integer := 625
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of worker_create_COO_matrix_1_1_1_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem : mem_array := (
    0 to 6=> "00000000000000000000000000000000", 
    7 => "01000000100111001000101101101110", 
    8 to 26=> "00000000000000000000000000000000", 
    27 => "11000001000101111111110111001101", 
    28 to 50=> "00000000000000000000000000000000", 
    51 => "01000000011001111111001001010110", 
    52 to 76=> "00000000000000000000000000000000", 
    77 => "11000000100111111011101000011010", 
    78 to 136=> "00000000000000000000000000000000", 
    137 => "11000000111010010000010000100010", 
    138 to 170=> "00000000000000000000000000000000", 
    171 => "01000001000010101100100000001000", 
    172 to 203=> "00000000000000000000000000000000", 
    204 => "01000000100011100010011000000000", 
    205 to 231=> "00000000000000000000000000000000", 
    232 => "11000001000001011101111010110011", 
    233 to 238=> "00000000000000000000000000000000", 
    239 => "00111111100010110110111000110011", 
    240 to 318=> "00000000000000000000000000000000", 
    319 => "10111111101000101000011100000010", 
    320 to 358=> "00000000000000000000000000000000", 
    359 => "11000000101111010100101100111001", 
    360 to 546=> "00000000000000000000000000000000", 
    547 => "01000000101101011110001101000111", 
    548 to 580=> "00000000000000000000000000000000", 
    581 => "11000000011100001000100111000010", 
    582 to 624=> "00000000000000000000000000000000" );


attribute EQUIVALENT_REGISTER_REMOVAL : string;
begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity worker_create_COO_matrix_1_1_1 is
    generic (
        DataWidth : INTEGER := 32;
        AddressRange : INTEGER := 625;
        AddressWidth : INTEGER := 10);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of worker_create_COO_matrix_1_1_1 is
    component worker_create_COO_matrix_1_1_1_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    worker_create_COO_matrix_1_1_1_rom_U :  component worker_create_COO_matrix_1_1_1_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


